--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2026-02-06 16:44:26

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE movimientos;
--
-- TOC entry 3346 (class 1262 OID 44542)
-- Name: movimientos; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE movimientos WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Ecuador.1252';


ALTER DATABASE movimientos OWNER TO postgres;

\connect movimientos

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 44544)
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    cliente_id integer NOT NULL,
    direccion character varying(255),
    edad integer,
    genero character varying(20),
    identificacion character varying(10),
    nombre character varying(100) NOT NULL,
    telefono character varying(10),
    contrasena character varying(255) NOT NULL,
    estado boolean NOT NULL
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 44543)
-- Name: clientes_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes ALTER COLUMN cliente_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 44551)
-- Name: cuentas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuentas (
    numero_cuenta character varying(20) NOT NULL,
    estado boolean NOT NULL,
    saldo numeric(19,4) NOT NULL,
    saldo_inicial numeric(19,4) NOT NULL,
    tipo_cuenta character varying(20) NOT NULL,
    cliente_id integer NOT NULL,
    CONSTRAINT cuentas_tipo_cuenta_check CHECK (((tipo_cuenta)::text = ANY ((ARRAY['AHORROS'::character varying, 'CORRIENTE'::character varying])::text[])))
);


ALTER TABLE public.cuentas OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 44558)
-- Name: movimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimientos (
    id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    saldo numeric(19,4) NOT NULL,
    tipo_movimiento character varying(20) NOT NULL,
    valor numeric(19,4) NOT NULL,
    numero_cuenta character varying(20) NOT NULL,
    CONSTRAINT movimientos_tipo_movimiento_check CHECK (((tipo_movimiento)::text = ANY ((ARRAY['CREDITO'::character varying, 'DEBITO'::character varying])::text[])))
);


ALTER TABLE public.movimientos OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 44557)
-- Name: movimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3337 (class 0 OID 44544)
-- Dependencies: 215
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.clientes VALUES (2, 'Otavalo sn y principal', 28, 'MASCULINO', '1234567892', 'Jose Lema', '098254785', '$2a$10$SLEcxHdbImCzmkMofVlgWeGVv3.n3RfaWplXJM7nDdc5wr8VPnRmK', true);
INSERT INTO public.clientes VALUES (3, '13 junio y Equinoccial', 25, 'MASCULINO', '7894561235', 'Juan Osorio', '098874587', '$2a$10$9pQunIhEDKrQvAdkCHD7EuzNPBAyM.Skl49f8tPctsDopuQKoRSZa', true);
INSERT INTO public.clientes VALUES (1, 'Amazonas y NNUU', 30, 'FEMENINO', '5587946859', 'Marianela Montalvo', '097548965', '$2a$10$lK19taiWlU8BI4bVlDfR9uium8JxKYg.Y9f8kCAdkd4VfXRuW4oGW', true);


--
-- TOC entry 3338 (class 0 OID 44551)
-- Dependencies: 216
-- Data for Name: cuentas; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.cuentas VALUES ('585545', true, 1000.0000, 1000.0000, 'CORRIENTE', 2);
INSERT INTO public.cuentas VALUES ('478758', true, 2385.0000, 2000.0000, 'AHORROS', 2);


--
-- TOC entry 3340 (class 0 OID 44558)
-- Dependencies: 218
-- Data for Name: movimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.movimientos VALUES (1, '2026-02-06 01:47:57.820186', 2100.0000, 'CREDITO', 100.0000, '478758');
INSERT INTO public.movimientos VALUES (2, '2026-02-06 01:48:29.388868', 2200.0000, 'CREDITO', 100.0000, '478758');
INSERT INTO public.movimientos VALUES (3, '2026-02-06 02:09:02.653476', 2185.0000, 'DEBITO', -15.0000, '478758');
INSERT INTO public.movimientos VALUES (4, '2026-02-06 02:09:22.596992', 2385.0000, 'CREDITO', 200.0000, '478758');


--
-- TOC entry 3347 (class 0 OID 0)
-- Dependencies: 214
-- Name: clientes_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_cliente_id_seq', 3, true);


--
-- TOC entry 3348 (class 0 OID 0)
-- Dependencies: 217
-- Name: movimientos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimientos_id_seq', 4, true);


--
-- TOC entry 3185 (class 2606 OID 44550)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (cliente_id);


--
-- TOC entry 3189 (class 2606 OID 44556)
-- Name: cuentas cuentas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT cuentas_pkey PRIMARY KEY (numero_cuenta);


--
-- TOC entry 3191 (class 2606 OID 44563)
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id);


--
-- TOC entry 3187 (class 2606 OID 44565)
-- Name: clientes ukmvqpaay4xno9pnlalro0awadi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT ukmvqpaay4xno9pnlalro0awadi UNIQUE (identificacion);


--
-- TOC entry 3192 (class 2606 OID 44566)
-- Name: cuentas fk65yk2321jpusl3fk96lqehrli; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT fk65yk2321jpusl3fk96lqehrli FOREIGN KEY (cliente_id) REFERENCES public.clientes(cliente_id);


--
-- TOC entry 3193 (class 2606 OID 44571)
-- Name: movimientos fko5koqjuegcyto02t8ytlf3y80; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT fko5koqjuegcyto02t8ytlf3y80 FOREIGN KEY (numero_cuenta) REFERENCES public.cuentas(numero_cuenta);


-- Completed on 2026-02-06 16:44:26

--
-- PostgreSQL database dump complete
--

